baseURL = 'https://www.greenzero.dev/'
languageCode = 'en-us'
title = 'Green Zero Development'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'rss']

[sitemap]
  changeFreq = ''
  disable = false
  filename = 'sitemap.xml'
  priority = -1